DROP DATABASE IF EXISTS db_ip;
CREATE DATABASE db_ip;

DROP TABLE IF EXISTS db_ip.ip;
CREATE TABLE db_ip.ip(
  id     INT AUTO_INCREMENT PRIMARY KEY COMMENT 'id PK',
start VARCHAR(255) NOT NULL COMMENT '起始IP',
end VARCHAR(255) NOT NULL COMMENT '终止IP',
address VARCHAR(255) NOT NULL COMMENT 'IP地址');
INSERT INTO db_ip.ip VALUES (NULL ,'起始IP','终止IP','IP地址');
SELECT *FROM db_ip.ip;